# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
name: Build and Deploy ASP.Net Core App to Azure Web App - AlphaStockData

on:
  push:
    branches:
      - v5.3
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Set up .NET Core SDK
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x' # Ensure this matches your project SDK version

      # Step 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore ./StockDataWebsite.sln

      # Step 4: Build the solution
      - name: Build with dotnet
        run: dotnet build ./StockDataWebsite.sln --configuration Release --no-restore

      # Step 5: Publish the application
      - name: Publish the application
        run: dotnet publish ./StockDataWebsite.sln --configuration Release --no-build --output ./publish

      # Step 6: Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A4B26381183746D2A88485E21629DC26 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_26085E748555404F8313329CD5326AFC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8A80DED398864F07B1F6C8F492F63449 }}

      # Step 7: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'AlphaStockData' # Replace with your actual App Service name
          slot-name: 'Production'
          package: ./publish

